### ISSUE TITLE
sadedegel-build-vocabulary command fails in latest release

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#125]
Also there is a typo in the command name `sadedegel-built-vocabulary` it should be `...-build-...`

<img width="1181" alt="Screen Shot 2020-10-07 at 17 58 19" src="https://user-images.githubusercontent.com/25409216/95348741-ff9da380-08c6-11eb-8872-d4a4a8d654ab.png">

**Comment by askarbozcan** [comment]
I fixed it in tok_vocabulary branch.
See #108

**Comment by dafajon** [comment]
Now it makes sense that PR is not reviewed and merged. I have been working on finalizing it when I discovered it. Pulling and merging the latest develop probably rewrited your fix. Can you please repeat your fix over latest develop by merging it to the PR branch and commit it, if you haven't done it yet.

**Comment by husnusensoy** [comment]
Can you retest with 0.15.2 version.

**Comment by dafajon** [comment]
I tested, it works. The typo is still present though in `setup.py`.

**Comment by husnusensoy** [comment]
Please update sadedegel 0.15.2.2 fix

**Comment by dafajon** [comment]
Done. Bug and typo are both fixed. Thanks.
